### ISSUE TITLE
Issue importing into Zabbix v3

### ISSUE THREAD

**Issue by phillip-white-sociomantic** [wisenetman/Zabbix-Templates#3]
While importing into Zabbix 3.0, i have this error:

`Invalid tag "/zabbix_export/version": unsupported version number.`

And changing the template from `<version>3.2</version>` to `<version>3.0</version>` i get `Invalid tag "/zabbix_export/templates/template(1)": unexpected tag "httptests".`

**Comment by mahdiafa** [comment]
Hi
I have this problem too

**Comment by madhusudany2k** [comment]
Any fix ?

**Comment by YiFenZ** [comment]
i make a pull request to fix this

**Comment by Yebolin** [comment]
> Any fix ?

https://github.com/Yebolin/Zabbix-Templates
